
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdbname
    ports:
      - "5432:5432"
    networks:
      - backend  # backend 네트워크에 연결
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash start.sh  # start.sh 스크립트 실행
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
      - DATABASE_URL=postgresql://postgres:DPFVjyYdmBOGUSeMikjNwIlzmZwDEprQ@centerbeam.proxy.rlwy.net:12483/railway
      - DJANGO_SETTINGS_MODULE=backend.settings
      - PYTHONUNBUFFERED=1
    networks:
      - backend  # backend 네트워크에 연결

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    environment:
      - TZ=Asia/Seoul
    networks:
      - backend  # backend 네트워크에 연결

  celery:
    build: .
    command: celery -A backend worker -l info  # Celery worker 실행
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    networks:
      - backend  # backend 네트워크에 연결

  celery-beat:
    build: .
    command: celery -A backend beat -l info  # Celery Beat 실행
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    networks:
      - backend  # backend 네트워크에 연결

networks:
  backend:  # 네트워크 정의
    driver: bridge  # 기본 브리지 네트워크 사용

volumes:
  postgres_data: