
services:
  web:
    build: .
    command: bash start.sh  # start.sh 스크립트 실행
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
      # Django가 .env를 못 읽는 상황 대비(확실하게)
      - DJANGO_SETTINGS_MODULE=backend.settings
      - PYTHONUNBUFFERED=1  # 따옴표 필요 없으므로 제거

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    environment:
      - TZ=Asia/Seoul

  celery:
    build: .
    command: bash start.sh  # start.sh 스크립트 실행
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul

  celery-beat:
    build: .
    command: bash start.sh  # start.sh 스크립트 실행
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul